#!/bin/bash
WORK_DIR="/tmp"
OUTPUT_DIR="/mnt/media/Movies"
SOURCE_DRIVE="/dev/sr0"
HANDBRAKE_PRESET="Normal"
EXTENSION="mkv"
LOG_DIR="/mnt/media/tempfiles/Movies/Logs"
LOG="movies.txt"
function rip_dvd() {
 # Use the disc title
 DVD_TITLE=$(blkid -o value -s LABEL $SOURCE_DRIVE)
 # Replace spaces with underscores
 DVD_TITLE=${DVD_TITLE// /_}
 if [ $DVD_TITLE == "DVD_VIDEO" ] 
 then
  echo -n "Movie title? "
  read line
  DVD_TITLE=$line
 fi
# Backup the DVD to hard drive
 dvdbackup -i $SOURCE_DRIVE -o $WORK_DIR -M -n $DVD_TITLE > $LOG_DIR/$DVD_TITLE-DVDBACKUP.log

 # pop out the disc
 eject $SOURCE_DRIVE

 # grep for the HandBrakeCLI process and get the PID
 HANDBRAKE_PID=`ps aux|grep H\[a\]ndBrakeCLI`
 set -- $HANDBRAKE_PID
 HANDBRAKE_PID=$2
# Wait until any existing Handbrake job is done
 if [ -n "$HANDBRAKE_PID" ]
 then
 while [ -e /proc/$HANDBRAKE_PID ]; do sleep 1; done
 fi
# Encode
 mkdir $OUTPUT_DIR/$DVD_TITLE
 HandBrakeCLI -i $WORK_DIR/$DVD_TITLE --main-feature -o $OUTPUT_DIR/$DVD_TITLE/$DVD_TITLE.$EXTENSION --preset=$HANDBRAKE_PRESET -s "1,2,3,4,5,6" > $LOG_DIR/$DVD_TITLE-HANDBRAKE.log
rm -R $WORK_DIR/$DVD_TITLE

 # Write to log & send PushBullet notification so Mr. Thumbs can change the disc
 noti -p -t "Finished ripping $DVD_TITLE" echo $DVD_TITLE >> $LOG_DIR/$LOG
}
rip_dvd

